importScripts("publisher-client.js");
const ENDPOINT="https://www.yoursparklesuite.com/api/live-lineup/publish",KEY="sparklePublisherV2",SOURCE="sparkleSourceV2",POPUP=chrome.runtime.getURL("popup.html");
const CREDENTIAL=/^(?:sslp_[A-Za-z0-9_-]{43}|[A-Z0-9]{3}-[0-9]{4})$/,CODE=/^[A-Z0-9]{3}-[0-9]{4}$/,PARTY=/^[A-Za-z0-9][A-Za-z0-9_-]{0,60}$/;
const safeCodes=new Set(["unauthorized","lease_expired","lease_required","publisher_conflict","revision_conflict","stale_sequence","rate_limited","invalid_payload","show_changed","invalid_scope","configuration_changed","source_not_ready"]);
const fail=code=>Object.assign(new Error(code),{code});let serial=Promise.resolve(),requesting=false,lastRequest=0,activePull=null;
function invalidatePull(tabId){if(activePull&&(tabId===undefined||activePull.tabId===tabId)){activePull.invalidated=true;for(const c of activePull.controllers)c.abort()}}
const baseReady=Promise.all([chrome.storage.local.setAccessLevel({accessLevel:"TRUSTED_CONTEXTS"}),chrome.storage.session.setAccessLevel({accessLevel:"TRUSTED_CONTEXTS"})]);
async function migrate(){const current=(await chrome.storage.local.get(KEY))[KEY]||null;let legacy={};try{legacy=await chrome.storage.sync.get(["sync_code","enabled","excluded_party_ids"])}catch{}
  if(!current&&CODE.test(legacy.sync_code||"")){await chrome.storage.local.set({[KEY]:{token:legacy.sync_code,enabled:legacy.enabled!==false,excludedPartyIds:Array.isArray(legacy.excluded_party_ids)?legacy.excluded_party_ids.filter(x=>PARTY.test(x)).slice(0,100):[],workflowVersion:3,configVersion:crypto.randomUUID(),claimId:null,nextSequence:0,needsClaim:true,nextAttemptAt:0}});return}
  if(current&&current.workflowVersion!==3){const unfinished=CODE.test(current.token||"")&&!Number.isSafeInteger(current.generation)&&!current.claimId;await chrome.storage.local.set({[KEY]:{...current,enabled:unfinished?true:Boolean(current.enabled),excludedPartyIds:Array.isArray(current.excludedPartyIds)?current.excludedPartyIds:[],workflowVersion:3,configVersion:crypto.randomUUID(),needsSelection:false,nextAttemptAt:0}})}
}
const ready=baseReady.then(migrate);ready.catch(()=>{});
function exclusive(task){const result=serial.then(()=>ready).then(task);serial=result.catch(()=>{});return result}
function bpUrl(value){try{const u=new URL(value);return u.origin==="https://myoffice.bombparty.com"&&u.pathname==="/live-party-orders"}catch{return false}}
const store={async load(){return(await chrome.storage.local.get(KEY))[KEY]||null},async update(version,patch){const state=await this.load();if(!state||state.configVersion!==version)return false;await chrome.storage.local.set({[KEY]:{...state,...patch}});return true}};
async function post(token,body,guard=null){if(guard?.invalidated)throw fail("configuration_changed");if(!CREDENTIAL.test(token))throw fail("unauthorized");const encoded=JSON.stringify(body);if(new TextEncoder().encode(encoded).byteLength>4194304)throw fail("invalid_payload");const limit=["describe","configure"].includes(body.action)?524288:16384,controller=new AbortController();guard?.controllers.add(controller);let timer,reader;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(fail("connection_failed"))},10000)});const work=async()=>{const response=await fetch(ENDPOINT,{method:"POST",redirect:"error",credentials:"omit",cache:"no-store",headers:{"Content-Type":"application/json","Authorization":"Bearer "+token},body:encoded,signal:controller.signal});if(response.redirected||response.url!==ENDPOINT)throw fail("invalid_receipt");if((response.headers.get("content-type")||"").split(";")[0].trim().toLowerCase()!=="application/json"||!response.body)throw fail("invalid_receipt");reader=response.body.getReader();const decoder=new TextDecoder("utf-8",{fatal:true});let count=0,text="";for(;;){const chunk=await reader.read();if(chunk.done)break;count+=chunk.value.byteLength;if(count>limit)throw fail("invalid_receipt");text+=decoder.decode(chunk.value,{stream:true})}text+=decoder.decode();let value;try{value=JSON.parse(text)}catch{throw fail("invalid_receipt")}if(!value||typeof value!=="object"||Array.isArray(value))throw fail("invalid_receipt");if(!response.ok)throw fail(response.status===401?"unauthorized":safeCodes.has(value.error)?value.error:"connection_failed");if(guard?.invalidated)throw fail("configuration_changed");return value};try{return await Promise.race([work(),timeout])}catch(error){if(guard?.invalidated)throw fail("configuration_changed");throw fail(safeCodes.has(error?.code)||error?.code==="invalid_receipt"?error.code:"connection_failed")}finally{guard?.controllers.delete(controller);clearTimeout(timer);controller.abort();if(reader)void reader.cancel().catch(()=>{})}}
function cleanDescriptor(value){if(!value||value.protocol!==2||!Number.isSafeInteger(value.generation)||value.generation<0||typeof value.serverTime!=="string"||!Number.isFinite(Date.parse(value.serverTime)))throw fail("invalid_receipt");if(value.generation===0&&value.scope===null)return{protocol:2,generation:0,scope:null,serverTime:value.serverTime};const s=value.scope;if(value.generation===0||!s||!Array.isArray(s.partyIds)||!s.partyIds.length||s.partyIds.length>100||!s.partyIds.every(x=>PARTY.test(x))||new Set(s.partyIds).size!==s.partyIds.length||!Array.isArray(s.excludedPartyIds)||s.excludedPartyIds.some(x=>!s.partyIds.includes(x))||new Set(s.excludedPartyIds).size!==s.excludedPartyIds.length||typeof s.startedAt!=="string"||!Number.isFinite(Date.parse(s.startedAt))||!Array.isArray(s.carryEntryIds)||s.carryEntryIds.length>2000)throw fail("invalid_receipt");return{protocol:2,generation:value.generation,scope:{partyIds:[...s.partyIds],excludedPartyIds:[...s.excludedPartyIds],startedAt:s.startedAt,carryEntryIds:[...s.carryEntryIds]},serverTime:value.serverTime}}
async function describe(state){state=state||await store.load();if(!state||!CREDENTIAL.test(state.token))throw fail("unauthorized");return cleanDescriptor(await post(state.token,{action:"describe"},activePull))}
const publisher=SparklePublisherClient.createPublisherClient({store,post:(token,body)=>post(token,body,activePull)});
async function selected(){return(await chrome.storage.session.get(SOURCE))[SOURCE]||null}async function clearSource(){await chrome.storage.session.remove(SOURCE)}
function summarize(snapshot){const map=new Map();const add=(id,open)=>{if(typeof id!=="string")return;const parts=id.split(":");if(parts.length!==2||!PARTY.test(parts[0]))return;const row=map.get(parts[0])||{id:parts[0],orderCount:0,unrevealedCount:0};row.orderCount++;if(open)row.unrevealedCount++;map.set(parts[0],row)};for(const entry of snapshot?.entries||[])add(entry.id,true);for(const id of snapshot?.revealedIds||[])add(id,false);return[...map.values()].sort((a,b)=>a.id.localeCompare(b.id))}
async function tabs(){const all=await chrome.tabs.query({url:"https://myoffice.bombparty.com/live-party-orders*"});return all.filter(t=>Number.isSafeInteger(t.id)&&bpUrl(t.url)).sort((a,b)=>Number(Boolean(b.active))-Number(Boolean(a.active))||a.id-b.id)}
async function messageTab(tabId,message){let timer;return Promise.race([chrome.tabs.sendMessage(tabId,message,{frameId:0}),new Promise((_,reject)=>{timer=setTimeout(()=>reject(fail("source_unavailable")),3000)})]).finally(()=>clearTimeout(timer))}
async function inspect(tabId){const response=await messageTab(tabId,{action:"sparkle-v2-inspect"});if(response?.protocol!==2)throw fail("source_unavailable");return response.snapshot}
async function read(tabId,descriptor){const response=await messageTab(tabId,{action:"sparkle-v2-read",selection:descriptor.scope,generation:descriptor.generation});if(response?.protocol!==2||response.generation!==descriptor.generation)throw fail("source_unavailable");return response.snapshot}
async function adopt(state,descriptor,source,parties){const changed=state.generation!==descriptor.generation,nextVersion=crypto.randomUUID();await chrome.storage.session.set({[SOURCE]:{tabId:source.tabId,generation:descriptor.generation,selection:descriptor.scope,parties}});if(!await store.update(state.configVersion,{configVersion:nextVersion,generation:descriptor.generation,needsSelection:false,authFailed:false,lastError:null,workflowVersion:3,...(changed?{claimId:null,epoch:null,publisherId:null,nextSequence:0,needsClaim:true,nextAttemptAt:0}: {})}))throw fail("configuration_changed");return await store.load()}
async function configure(state,descriptor,parties){const detected=parties.map(x=>x.id),excluded=(state.excludedPartyIds||[]).filter(x=>detected.includes(x));return cleanDescriptor(await post(state.token,{action:"configure",generation:descriptor.generation,partyIds:detected,excludedPartyIds:excluded},activePull))}
async function prepare(){let state=await store.load();if(!state?.enabled)return null;let descriptor=await describe(state),source=await selected(),choices=await tabs();if(!choices.length){await clearSource();return null}const tab=choices.find(x=>x.id===source?.tabId)||choices[0];activePull.tabId=tab.id;const full=await inspect(tab.id),parties=summarize(full);if(!parties.length){if(source?.parties?.length&&full?.parserState!=="ready"){state=await adopt(state,descriptor,{tabId:tab.id},source.parties);return{state,descriptor,parties:source.parties,snapshot:full,tabId:tab.id}}if(descriptor.generation>0&&source?.parties?.length){state=await adopt(state,descriptor,{tabId:tab.id},source.parties);return{state,descriptor,parties:source.parties,snapshot:await read(tab.id,descriptor),tabId:tab.id}}await chrome.storage.session.set({[SOURCE]:{tabId:tab.id,generation:descriptor.generation,selection:descriptor.scope,parties:[]}});await store.update(state.configVersion,{parserState:full?.parserState||"partial",lastError:null});return null}
  if(descriptor.generation>0){const detected=parties.map(x=>x.id),scope=descriptor.scope,desired=(state.excludedPartyIds||[]).filter(x=>detected.includes(x)),current=scope.excludedPartyIds.filter(x=>detected.includes(x));if(detected.some(x=>!scope.partyIds.includes(x))||desired.join("\0")!==current.join("\0"))descriptor=await configure(state,descriptor,parties)}
  state=await adopt(state,descriptor,{tabId:tab.id},parties);return{state,descriptor,parties,snapshot:descriptor.generation===0?full:await read(tab.id,descriptor),tabId:tab.id}}
async function status(){const state=await store.load(),source=await selected(),age=state?.lastReadyAckAt==null?null:Date.now()-state.lastReadyAckAt;return{ok:true,configured:Boolean(state&&CREDENTIAL.test(state.token)),enabled:Boolean(state?.enabled),code:CODE.test(state?.token||"")?state.token:"",parties:Array.isArray(source?.parties)?source.parties:[],excludedPartyIds:Array.isArray(state?.excludedPartyIds)?state.excludedPartyIds:[],connected:Boolean(state?.enabled&&source?.parties?.length&&state?.parserState==="ready"&&age!==null&&age>=0&&age<=45000&&!state?.lastError),lastAckAt:state?.lastAckAt??null,lastReadyAckAt:state?.lastReadyAckAt??null,lastError:state?.lastError??null,needsConnection:Boolean(state?.authFailed)}}
async function pull(){const guard={tabId:null,invalidated:false,controllers:new Set()};activePull=guard;try{const prepared=await prepare();if(!prepared)return{status:"waiting"};const result=await publisher.sync(prepared.snapshot,chrome.runtime.getManifest().version);if(result?.status==="confirmed"&&prepared.descriptor.generation===0){const state=await store.load(),descriptor=await configure(state,prepared.descriptor,prepared.parties);await adopt(state,descriptor,{tabId:prepared.tabId},prepared.parties)}return result}catch(error){const state=await store.load();if(state)await store.update(state.configVersion,{lastError:error?.code||"source_unavailable",...(error?.code==="unauthorized"?{authFailed:true}:{})});return{status:guard.invalidated?"source_changed":"source_unavailable"}}finally{if(activePull===guard)activePull=null}}
function requestPull(){if(requesting||(Date.now()>=lastRequest&&Date.now()-lastRequest<700))return Promise.resolve({status:"busy"});requesting=true;lastRequest=Date.now();return exclusive(pull).finally(()=>{requesting=false})}
async function popupMessage(message){if(message.action==="sparkle-v2-status")return status();if(message.action==="sparkle-v2-connect"){const credential=typeof message.credential==="string"?message.credential.toUpperCase():"";if(!CODE.test(credential))return{ok:false,error:"invalid_token"};const previous=await store.load(),candidate={token:credential,enabled:true,excludedPartyIds:[],workflowVersion:3,configVersion:crypto.randomUUID(),claimId:null,nextSequence:0,needsClaim:true,nextAttemptAt:0,authFailed:false};await chrome.storage.local.set({[KEY]:candidate});try{await describe(candidate)}catch(error){if(previous)await chrome.storage.local.set({[KEY]:previous});else await chrome.storage.local.remove(KEY);return{ok:false,error:error?.code||"connection_failed"}}await clearSource();return status()}
  if(message.action==="sparkle-v2-toggle"){const state=await store.load();if(!state||typeof message.enabled!=="boolean")return{ok:false,error:"invalid_action"};if(!await store.update(state.configVersion,{enabled:message.enabled,nextAttemptAt:0,lastError:null}))throw fail("configuration_changed");return status()}
  if(message.action==="sparkle-v2-filter"){let state=await store.load(),source=await selected();if(!state||!source||!PARTY.test(message.partyId)||typeof message.included!=="boolean"||!source.parties?.some(x=>x.id===message.partyId))return{ok:false,error:"invalid_action"};const excluded=new Set(state.excludedPartyIds||[]);message.included?excluded.delete(message.partyId):excluded.add(message.partyId);if(!await store.update(state.configVersion,{excludedPartyIds:[...excluded].sort(),nextAttemptAt:0}))throw fail("configuration_changed");state=await store.load();if(source.generation>0){const descriptor=await configure(state,await describe(state),source.parties);await adopt(state,descriptor,source,source.parties)}return status()}return{ok:false,error:"invalid_action"}}
chrome.runtime.onMessage.addListener((message,sender,respond)=>{if(sender.id!==chrome.runtime.id||!message||typeof message!=="object")return false;if(!sender.tab&&sender.url===POPUP){if(["sparkle-v2-connect","sparkle-v2-toggle","sparkle-v2-filter"].includes(message.action))invalidatePull();exclusive(()=>popupMessage(message)).then(result=>{respond(result);if(result.ok&&["sparkle-v2-connect","sparkle-v2-toggle","sparkle-v2-filter"].includes(message.action)){lastRequest=0;void requestPull().catch(()=>{})}},()=>respond({ok:false,error:"operation_failed"}));return true}if(message.action==="sparkle-v2-changed"&&sender.frameId===0&&sender.tab&&bpUrl(sender.url)){ready.then(()=>requestPull()).then(()=>respond({ok:true}),()=>respond({ok:false}));return true}return false});
chrome.alarms.onAlarm.addListener(a=>{if(a.name==="sparkle-sync")void requestPull().catch(()=>{})});chrome.tabs.onRemoved.addListener(tabId=>{invalidatePull(tabId);void exclusive(async()=>{if((await selected())?.tabId===tabId)await clearSource()}).then(()=>requestPull()).catch(()=>{})});chrome.tabs.onUpdated.addListener((tabId,change)=>{if(change.status==="loading"||change.url)invalidatePull(tabId);if(change.status==="complete"||change.url){lastRequest=0;void requestPull().catch(()=>{})}});chrome.tabs.onActivated?.addListener(()=>{lastRequest=0;void requestPull().catch(()=>{})});ready.then(()=>chrome.alarms.create("sparkle-sync",{periodInMinutes:.5})).then(()=>requestPull()).catch(()=>{});
