(function(){"use strict";
const el=id=>document.getElementById(id);let busy=false,state=null;
const copy={invalid_token:"Enter the complete Live Queue code from your Workspace.",unauthorized:"That Live Queue code was not recognized.",connection_failed:"Sparkle Suite could not be reached. Your current lineup is safe.",operation_failed:"That change could not be confirmed. Please try again.",publisher_conflict:"This Live Lineup is connected in another browser. Turn it off there, then try again."};
const fail=code=>Object.assign(new Error(code),{code});
async function send(message){let timer;try{const result=await Promise.race([chrome.runtime.sendMessage(message),new Promise((_,reject)=>{timer=setTimeout(()=>reject(fail("operation_failed")),15000)})]);if(!result||result.ok!==true)throw fail(result?.error||"operation_failed");return result}finally{clearTimeout(timer)}}
function valid(value){return value&&typeof value.configured==="boolean"&&typeof value.enabled==="boolean"&&typeof value.needsConnection==="boolean"&&typeof value.code==="string"&&Array.isArray(value.parties)&&Array.isArray(value.excludedPartyIds)}
function partyRow(p,excluded){const label=document.createElement("label");label.className="party";const box=document.createElement("input");box.type="checkbox";box.checked=!excluded.includes(p.id);box.dataset.partyId=p.id;box.disabled=busy;const text=document.createElement("span");text.textContent="Party "+p.id;const detail=document.createElement("small");detail.textContent=p.orderCount+" order"+(p.orderCount===1?"":"s");text.appendChild(detail);label.append(box,text);return label}
function render(value){if(!valid(value))throw fail("operation_failed");state=value;el("connect-card").hidden=value.configured&&!value.needsConnection;el("lineup-card").hidden=!value.configured||value.needsConnection;el("saved-code").textContent=value.code||"Saved";el("enabled").checked=value.enabled;el("enabled").disabled=busy;let title="Waiting for Party Orders",detail="Open your Bomb Party Party Orders page.",tone="warn";if(!value.enabled){title="Paused";detail="Turn Live Lineup on when you are ready.";tone=""}else if(value.lastError||value.needsConnection){title="Connection needs attention";detail="Your existing lineup is safe while Sparkle Suite reconnects.";tone="bad"}else if(value.connected){title="Connected";detail="Live Lineup is keeping up with your orders.";tone="good"}el("status-text").textContent=title;el("status-detail").textContent=detail;el("status-dot").className="dot "+tone;const parties=el("parties");parties.replaceChildren();if(!value.parties.length){const empty=document.createElement("p");empty.className="empty";empty.textContent="No parties detected yet.";parties.appendChild(empty)}else for(const p of value.parties)parties.appendChild(partyRow(p,value.excludedPartyIds))}
function showError(error){el("error").textContent=copy[error?.code]||"That change could not be confirmed. Your existing lineup is safe."}
async function act(task){if(busy)return;busy=true;el("controls").disabled=true;el("error").textContent="";try{render(await task())}catch(error){showError(error)}finally{busy=false;el("controls").disabled=false;if(state)render(state)}}
el("connect-form").addEventListener("submit",event=>{event.preventDefault();void act(async()=>{const credential=el("live-code").value.trim().toUpperCase();if(!/^[A-Z0-9]{3}-[0-9]{4}$/.test(credential))throw fail("invalid_token");const result=await send({action:"sparkle-v2-connect",credential});el("live-code").value="";return result})});
el("enabled").addEventListener("change",()=>{const enabled=el("enabled").checked;void act(()=>send({action:"sparkle-v2-toggle",enabled}))});
el("parties").addEventListener("change",event=>{const input=event.target;if(!(input instanceof HTMLInputElement)||!input.dataset.partyId)return;void act(()=>send({action:"sparkle-v2-filter",partyId:input.dataset.partyId,included:input.checked}))});
async function refresh(){if(busy)return;try{render(await send({action:"sparkle-v2-status"}))}catch(error){showError(error)}}
void refresh();const interval=setInterval(()=>void refresh(),2000);window.addEventListener("pagehide",()=>{clearInterval(interval);el("live-code").value=""})})();
