const copy = {invalid_token:"Enter the complete Live Queue code from your Workspace.",unauthorized:"That Live Queue code was not recognized.",connection_failed:"Sparkle Suite could not be reached. Your current lineup is safe.",operation_failed:"That change could not be confirmed. Please try again.",source_unavailable:"Open your Bomb Party Live Party Orders page. Sparkle Suite will reconnect automatically.",source_ambiguous:"Keep one Live Party Orders tab open so Sparkle Suite can select it automatically.",show_changed:"The party selection changed. Sparkle Suite is reading it again.",capacity_exceeded:"The lineup is full. Your existing orders are safe. The supported order limit has been reached.",publisher_conflict:"This Live Lineup is connected in another browser. Turn it off there, then try again."};
const reasons = {table_missing:"Waiting for the Live Party Orders table.",table_busy:"Bomb Party is updating its orders.",table_incomplete:"Waiting for Bomb Party to finish loading the table.",table_settling:"Waiting for the order table to finish changing.",selected_party_not_visible:"The selected parties are not visible in the order table.",reveal_state_missing:"An order's reveal checkbox is unavailable or still updating.",row_incomplete:"An order row has not finished loading.",columns_changed:"The Bomb Party table layout is not recognized.",missing_order_identity:"An order or party ID could not be read safely.",duplicate_order_identity:"Bomb Party returned duplicate order IDs.",invalid_order_time:"An order has an unreadable timestamp.",invalid_first_name:"An order's customer name could not be read safely.",capacity_exceeded:"The supported order limit has been reached.",scan_capacity_exceeded:"The order table is too large to read safely.",invalid_scope:"The party selection could not be validated."};
copy.lease_expired = "The connection lease expired. Sparkle Suite is reconnecting.";
copy.lease_required = copy.lease_expired;
copy.server_update_required = "This site has not received the matching Live Lineup server update yet.";
const RECONNECT_ERRORS = new Set(["lease_expired","lease_required","source_unavailable","connection_failed","show_changed","operation_failed"]);
const ROUTINE_REASONS = new Set(["table_busy","table_settling","table_incomplete","reveal_state_missing","row_incomplete"]);
const ATTENTION_REASONS = new Set(["columns_changed","missing_order_identity","duplicate_order_identity","invalid_order_time","invalid_first_name","capacity_exceeded","scan_capacity_exceeded","invalid_scope","selected_party_not_visible"]);
function hadReadyAck(value){return Number.isFinite(value.lastReadyAckAt)}
/** Popup status words only. Does not change parser, lease, publish, or read behavior. */
function extensionLineupStatus(value){
  if(!value.enabled) return {title:"Off",detail:"Turn Live Lineup on when you are ready.",tone:""};
  if(value.needsConnection || (value.lastError && !RECONNECT_ERRORS.has(value.lastError))) return {title:"Needs attention",detail:copy[value.lastError]||"Your existing lineup is safe while Sparkle Suite reconnects.",tone:"bad"};
  if(value.lastError && RECONNECT_ERRORS.has(value.lastError)) return {title:"Reconnecting",detail:copy[value.lastError],tone:"warn"};
  if(value.parserReason && ATTENTION_REASONS.has(value.parserReason) && !value.connected) return {title:"Needs attention",detail:reasons[value.parserReason]||"The order table could not yet be read safely.",tone:"bad"};
  if(value.connected) return {title:"Connected + Updating",detail:"Live Lineup is keeping up with your orders.",tone:"good"};
  if(value.scopePending && hadReadyAck(value)) return {title:"Connected + Updating",detail:"Waiting for a confirmed update of the selected parties.",tone:"good"};
  if(value.parserReason && ROUTINE_REASONS.has(value.parserReason) && hadReadyAck(value)) return {title:"Connected + Updating",detail:reasons[value.parserReason]||"The order table could not yet be read safely.",tone:"good"};
  if(hadReadyAck(value)) return {title:"Reconnecting",detail:value.parserReason ? (reasons[value.parserReason]||"The order table could not yet be read safely.") : "Sparkle Suite is reconnecting.",tone:"warn"};
  return {title:"Connecting",detail:value.parserReason ? (reasons[value.parserReason]||"The order table could not yet be read safely.") : "Open your Bomb Party Party Orders page.",tone:""};
}
(function(){"use strict";
const el=id=>document.getElementById(id);let busy=false,state=null;
const fail=code=>Object.assign(new Error(code),{code});
async function send(message){let timer;try{const result=await Promise.race([chrome.runtime.sendMessage(message),new Promise((_,reject)=>{timer=setTimeout(()=>reject(fail("operation_failed")),15000)})]);if(!result||result.ok!==true)throw fail(result?.error||"operation_failed");return result}finally{clearTimeout(timer)}}
function valid(value){return value&&typeof value.configured==="boolean"&&typeof value.enabled==="boolean"&&typeof value.needsConnection==="boolean"&&typeof value.code==="string"&&Array.isArray(value.parties)&&Array.isArray(value.excludedPartyIds)}
function partyRow(p,excluded){const label=document.createElement("label");label.className="party";const box=document.createElement("input");box.type="checkbox";box.checked=!excluded.includes(p.id);box.dataset.partyId=p.id;box.disabled=busy;const text=document.createElement("span");text.textContent="Party "+p.id;const detail=document.createElement("small");detail.textContent=p.orderCount+" order"+(p.orderCount===1?"":"s");text.appendChild(detail);label.append(box,text);return label}
function render(value){if(!valid(value))throw fail("operation_failed");state=value;el("connect-card").hidden=value.configured&&!value.needsConnection;el("lineup-card").hidden=!value.configured||value.needsConnection;el("saved-code").textContent=value.code||"Saved";el("enabled").checked=value.enabled;el("enabled").disabled=busy;const signal=extensionLineupStatus(value);el("status-text").textContent=signal.title;el("status-detail").textContent=signal.detail;el("status-dot").className="dot "+signal.tone;const parties=el("parties");parties.replaceChildren();if(!value.parties.length){const empty=document.createElement("p");empty.className="empty";empty.textContent="No parties detected yet.";parties.appendChild(empty)}else for(const p of value.parties)parties.appendChild(partyRow(p,value.excludedPartyIds))}
function showError(error){el("error").textContent=copy[error?.code]||"That change could not be confirmed. Your existing lineup is safe."}
async function act(task){if(busy)return;busy=true;el("controls").disabled=true;el("error").textContent="";try{render(await task())}catch(error){showError(error)}finally{busy=false;el("controls").disabled=false;if(state)render(state)}}
el("connect-form").addEventListener("submit",event=>{event.preventDefault();void act(async()=>{const credential=el("live-code").value.trim().toUpperCase();if(!/^[A-Z0-9]{3}-[0-9]{4}$/.test(credential))throw fail("invalid_token");const result=await send({action:"sparkle-v2-connect",credential});el("live-code").value="";return result})});
el("enabled").addEventListener("change",()=>{const enabled=el("enabled").checked;void act(()=>send({action:"sparkle-v2-toggle",enabled}))});
el("parties").addEventListener("change",event=>{const input=event.target;if(!(input instanceof HTMLInputElement)||!input.dataset.partyId)return;void act(()=>send({action:"sparkle-v2-filter",partyId:input.dataset.partyId,included:input.checked}))});
async function refresh(){if(busy)return;try{render(await send({action:"sparkle-v2-status"}))}catch(error){showError(error)}}
void refresh();const interval=setInterval(()=>void refresh(),2000);window.addEventListener("pagehide",()=>{clearInterval(interval);el("live-code").value=""})})();
